/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registrodeplatosdecomida;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author carlo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    private String nombre;
    private Conexion conexion;
    private Connection connect;
    
    public Interfaz() {
        initComponents();
        this.nombre="";
        this.conexion=new Conexion();
        this.connect=conexion.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonRegsitrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        Image img= new ImageIcon("C:\\Users\\carlo\\Pictures\\tarea1.jpg").getImage();
        ImageIcon img2=new ImageIcon(img.getScaledInstance(540, 470, Image.SCALE_SMOOTH));
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonRegsitrar.setBackground(new java.awt.Color(0, 153, 204));
        buttonRegsitrar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        buttonRegsitrar.setText("REGISTRAR");
        buttonRegsitrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegsitrarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRegsitrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 184, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRO DE COMIDA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 420, 47));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Nombre de la comida:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 240, -1));

        textNombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 370, 30));

        jLabel5.setIcon(img2);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 465));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegsitrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegsitrarActionPerformed
        // TODO add your handling code here:
        try {
            nombre=verificarNombre();
            if(verExistencia()==false){
                registrar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de registro :("+e.getMessage());
        }
        
    }//GEN-LAST:event_buttonRegsitrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegsitrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables

    private String verificarNombre() {
        String res="";
        res=textNombre.getText();
        return res;
    }
    private void registrar(){
        String sql="insert into platos(nombre) values (?)";
        try {
            PreparedStatement pst=connect.prepareStatement(sql);
            pst.setString(1,this.nombre);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Registro exitoso :)");
        } catch (Exception e) {
            
        }
    }
    private boolean verExistencia(){
        boolean res=false;
        String sql="select * from platos where nombre = '"+this.nombre+"'";
        try {
            Statement st=connect.createStatement();
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()){
                res=true;
                JOptionPane.showMessageDialog(null, "Error, ya existe: "+this.nombre);
            }
        } catch (Exception e) {
        }
        return res;
    }
    
    
}
